version: '3'

services:
  database:
    image: postgres:alpine
    network_mode: host
    environment:
      - POSTGRES_PASSWORD=12345
    volumes:
      - ./init.db.sql:/docker-entrypoint-initdb.d/init.db.sql
  server:
    image: node:latest
    network_mode: host
    user: node
    working_dir: /home/node/app
    volumes:
      - ./:/home/node/app
    depends_on:
      - database
    command: bash -c "npm i && npm start"
