version: '3'

services:
  db:
    image: postgres:alpine
    environment:
      - POSTGRES_PASSWORD=12345
    ports:
      - 5432:5432
    volumes:
      - ./init.db.sql:/docker-entrypoint-initdb.d/init.db.sql
      - ./data:/var/lib/postgresql/data
  api:
    image: node:latest
    user: "node"
    working_dir: /home/node/app
    environment:
      - NODE_ENV=production
    volumes:
      - ./:/home/node/app
    expose:
      - "3630"
    ports:
      - 3630:3630
    command: "npm start"
